project_name: terraform-provider-megaport

builds:
- binary: "terraform-provider-megaport_v{{.Version}}_x4"
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - windows
  - linux
  goarch:
  - amd64
  ldflags: []

archives:
  - name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"
    format_overrides:
    - goos: windows
      format: zip
    - goos: darwin
      format: zip
    - goos: linux
      format: zip
    files:
      - none*  # only package the binary

checksum:
  name_template: 'SHA256SUMS.txt'
